---
title: "Pandemi ve Artan harcamalar"
author: 
  - matin shahpalangov[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 21080688, [Github Repo](https://github.com/metinshahpalangov/arasinav)



# Giriş
2020 yılında tüm dünyayı etkisi altına alan COVID-19 pandemisi, sağlık hizmetlerinin önemini bir kez daha gösterdi. Pandeminin sebep olduğu sağlık sorunlarına yönelik hizmetlerin artması, sağlık harcamalarının da artmasına sebep oldu. Amerika Birleşik Devletleri'nde sağlık harcamaları 2020 yılında yüksek bir artış gösterirken, 2021 yılında artış oranı düşerek devam etti. Bu veriler pandemi döneminde artan sağlık harcamaları ve sağlık sektörüne yönelik devlet harcamalarının etkisini incelemek için önemli bir fırsat sunuyor.



## Çalışmanın Amacı
Bu projenin amacı, Amerika Birleşik Devletleri'nde pandemi döneminde artan sağlık harcamalarının ana sebeplerini ve bu harcamaların sağlık sektörüne etkilerini incelemektir. Bu amaç doğrultusunda aşağıdaki sorulara cevap aranacaktır:

Pandemi döneminde Amerika Birleşik Devletleri'nde sağlık harcamaları nasıl bir artış gösterdi?
Artışın ana sebepleri nelerdir?
Pandeminin sağlık sektörüne etkisi nedir?
Devlet harcamalarının artışa etkisi nedir?
Sağlık harcamalarındaki bu artışın gelecekteki etkileri nelerdir?

## Literatür 
Örneğin, American Medical Association (AMA) tarafından yayınlanan bir raporda, pandemi döneminde sağlık harcamalarının artış oranının 2.7% olduğu belirtilmektedir. Bu artışın ana sebebi, pandemi ile ilgili hükümet harcamalarındaki düşüşe rağmen, ertelenmiş sağlık hizmetlerinin ve pent-up talebin artmasıdır. Aynı raporda, sağlık harcamalarının 2021 yılında GSYİH'nin %18.3'üne karşılık geldiği belirtilmektedir.

Başka bir çalışmada, The Commonwealth Fund tarafından yayınlanan bir raporda, pandemi nedeniyle sağlık hizmetleri talebindeki artışın, hastanelerdeki yoğunluğun ve sağlık personeli eksikliğinin, özellikle de yoğun bakım ünitelerindeki eksik


**_Taslakta bu cümleden sonra yer alan hiçbir şey silinmemelidir._**

\newpage
# Kaynakça {#references}
<div id="refs"></div>

